title: push this !
description: learning software through my mistakes - brought to you by prettygirl69
author: pushthis
sass:
  style: compressed
  <link rel="stylesheet" href="{{ '/assets/css/style.css' | relative_url }}">
